### ISSUE TITLE
训练的时候 tcv train skirt_length_01.cfg 报错

### ISSUE THREAD

**Issue by sillytheif** [tworuler/tensorcv#1]
找不到 tcv这个命令......

**Comment by tworuler** [comment]
tcv是tensorcv的命令。需要安装下tensorcv，见README里面的安装部分。

**Comment by sillytheif** [comment]
谢谢，这个问题解决了。还有一个问题.....就是 训练的时候 报错 tensorflow.python.framework.errors_impl.NotFoundError: '/home/zrc/fashionai/data/train_data/Annotations/train.csv'; No such file or directory
但是我是有这个文件的.....

**Comment by tworuler** [comment]
读取训练数据的[代码](https://github.com/tworuler/tensorcv/blob/tianchi-fashionai/tensorcv/data/dataset/fashionai_attribute_dataset.py#L12)只是简单地调用了一下`tf.gfile.Open`，如果文件存在的话不应该会报这个错。`/home/zrc/fashionai/data/train_data/Annotations/train.csv`这个路径应该是你在配置文件里`[data]`下`train_data`的值。如果确认文件确实存在，还会报错，可能需要你提供更多的错误信息，我才能帮你看

**Comment by freehome1** [comment]
我也遇到了tensorflow.python.framework.errors_impl.NotFoundError: '~/fashionai/data/train_data/Annotations/train.csv'; No such file or directory这个错误

**Comment by tworuler** [comment]
@freehome1 把路径里的`~`换成`/home/xxx`试试 (`xxx`是你的用户名)

**Comment by freehome1** [comment]
我的fashionai是在根目录下的，改了试了下还是一样的- -

**Comment by tworuler** [comment]
@freehome1 根目录？所以不是你的home目录？你ls试下有没有这个文件
`ls ~/fashionai/data/train_data/Annotations/train.csv`

**Comment by freehome1** [comment]
额，就是我的/home/xxx文件夹下的。文件没问题的，顺便问下为什么会是skirt_length_01.cfg，是后来用resnet50后改了这个文件的名字么。在clone下来的GitHub中只有skirt_length.cfg，我train的这个文件

**Comment by freehome1** [comment]
尝试了下predict也是tensorflow.python.framework.errors_impl.NotFoundError: '~/fashionai/data/test_data/Tests/question.csv'; No such file or directory这个错误...

**Comment by tworuler** [comment]
@freehome1 train skirt_length.cfg没有问题，是我README里面文件名写错了。
我测了一下，路径里不能用`~`的，把`~`换成`/home/xxx`，如果是mac系统应该是`/Users/xxx`。还不行的话，给下你的系统版本和tensorflow版本吧。

再把报错的这行代码
https://github.com/tworuler/tensorcv/blob/af4ea3085056a77613c8e111facf0f12387b9655/tensorcv/data/dataset/fashionai_attribute_dataset.py#L30
换成
```
with open(path) as f:
```
看下还会不会报文件不存在

**Comment by freehome1** [comment]
我用的centos7系统，TensorFlow-gpu1.4.1，改目录一样的错误，改了这个代码报错：FileNotFoundError:'/home/tjj/fashionai/data/train_data/Annotations/train.csv',然后在tmp文件夹下全部重新操作也是这样。。

**Comment by freehome1** [comment]
可以了，非常感谢大佬

**Comment by YasinQiu** [comment]
请问:
我成功安装了tensorcv, 在/usr/local/lib/python3.6/dist-packages里可以看到安装好的tensorcv. 并且我把这个目录加入了环境变量中. 依然提示找不到tcv命令..........
