### ISSUE TITLE
 No module named 'tensorcv.command'

### ISSUE THREAD

**Issue by zjwzcn07** [tworuler/tensorcv#3]
执行
`tcv train skirt_length.cfg`
报错
```
Traceback (most recent call last):
  File "E:\Python35\Scripts\tcv-script.py", line 11, in <module>
    load_entry_point('tensorcv', 'console_scripts', 'tcv')()
  File "E:\Python35\lib\site-packages\pkg_resources\__init__.py", line 563, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "E:\Python35\lib\site-packages\pkg_resources\__init__.py", line 2651, in load_entry_point
    return ep.load()
  File "E:\Python35\lib\site-packages\pkg_resources\__init__.py", line 2305, in load
    return self.resolve()
  File "E:\Python35\lib\site-packages\pkg_resources\__init__.py", line 2311, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "E:\Python35\lib\site-packages\tensorcv\__init__.py", line 1, in <module>
    from tensorcv.command.cli import cli
ImportError: No module named 'tensorcv.command'
```
![tensorcv安装成功的提示](https://user-images.githubusercontent.com/15607152/37193443-e73575e8-23a4-11e8-9122-16971f1202e0.png)

已经按照requirements.txt安装好其他所需要的库，tf的版本是tensorflow_gpu-1.4.0，试过更新的版本1.6.0也不行。

**Comment by tworuler** [comment]
这个跟tensorflow的版本没有关系。我在windows 7下用python3.5.4测了下，不会有这样的问题。你是什么环境

**Comment by weixia-cs** [comment]
@zjwzcn07 我也遇到同样的问题，`No module named 'tensorcv.command'`，我是在linux下用python2.7 环境下运行的

**Comment by tworuler** [comment]
@weixia-cs 需要使用python3

**Comment by weixia-cs** [comment]
@tworuler 嗯嗯，已改用python3，旧问题解决了，但是又出现新问题了2333

**Comment by zjwzcn07** [comment]
@tworuler 我用的是win10+python3.5安装的requirement，启动tcv的时候应该会默认使用python3吧，报了这个错`No module named 'tensorcv.command'`

**Comment by tworuler** [comment]
@zjwzcn07 我觉得这是python2才会报的错，尝试做下面几件事
* 检查下`E:\Python35\Scripts\tcv-script.py`中的第一行是不是指向你python3的路径
* 如果python35是你启动python3的命令，尝试运行`python35 -c 'import tensorcv'`，看下是否会报错。如果不会报错，说明用python3启动没问题

**Comment by weixia-cs** [comment]
@tworuler 运行代码提示错误
` got an unexpected keyword argument ‘keep_checkpoiont_max’`  
` got an unexpected keyword argument ‘model_dir’`   
` got an unexpected keyword argument ‘save_summary_steps’`  ,
这三个错误轮流出现，我看代码是 tensorcv/train/trainer/trainer.py，但找了半天也没有解决，希望能帮我看看哪里出问题了

**Comment by tworuler** [comment]
@weixia-cs 检查下你有没有改过代码，有一个参数应该是`keep_checkpoint_max`，你这里给的错误信息是`keep_checkpoiont_max`。FYI: [tf.estimator.RunConfig的文档](https://www.tensorflow.org/api_docs/python/tf/estimator/RunConfig)

**Comment by weixia-cs** [comment]
@tworuler 代码检查过了，没有问题，`poiont`应该是单词打错了。我觉得可能是环境问题，,我的TensorFlow是1.2版本，没更新到1.4，想问下是不是必须要更新到1.4

**Comment by tworuler** [comment]
@weixia-cs 是的，tensorflow得要1.4或以上版本

**Comment by weixia-cs** [comment]
@tworuler 太感谢，代码终于跑起来了
