### ISSUE TITLE
想换个模型

### ISSUE THREAD

**Issue by wuhaotju** [tworuler/tensorcv#6]
请问 需要在哪里修改啊？ 你写的代码太专业了

**Comment by tworuler** [comment]
可以往`tensorcv/net`里面添加新的网络结构，参考对resnet的封装
https://github.com/tworuler/tensorcv/blob/af4ea3085056a77613c8e111facf0f12387b9655/tensorcv/net/resnet.py#L377-L379
再在`tensorcv/net/__init__.py`里注册一下，就可以在配置文件中使用新加的网络结构
https://github.com/tworuler/tensorcv/blob/af4ea3085056a77613c8e111facf0f12387b9655/tensorcv/net/__init__.py#L5-L8
