### ISSUE TITLE
成功安装tensorcv并添加环境变量, 依然报错找不到tcv命令

### ISSUE THREAD

**Issue by YasinQiu** [tworuler/tensorcv#8]
请问:
我成功安装了tensorcv, 在/usr/local/lib/python3.6/dist-packages里可以看到安装好的tensorcv. 并且我把这个目录加入了环境变量中. 依然提示找不到tcv命令..........
No command 'tcv' found, did you mean:
 Command 'pcv' from package 'picviz' (universe)
 Command 'tcm' from package 'tcm' (universe)
 Command 'tv' from package 'treeviewx' (universe)
 Command 'mcv' from package 'scotch' (universe)
 Command 'tcvt' from package 'tcvt' (universe)
 Command 'tcs' from package 'tcs' (universe)
 Command 'gcv' from package 'scotch' (universe)
 Command 'tcc' from package 'tcc' (universe)
 Command 'tc' from package 'iproute2' (main)
 Command 'ttv' from package 'ttv' (universe)
tcv: command not found

**Comment by tworuler** [comment]
检查下你python环境和安装方式有没有问题。
tensorcv安装的问题参考：https://github.com/tworuler/tensorcv/issues/1

**Comment by YasinQiu** [comment]
我是ubunut环境, 安装了两个python, 一个是2.7, 一个是3.6.3, 这两个都装的没问题~~
